[theme]
primaryColor = "#FF6600"  # Avanade Orange
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F8F8F8"  # Light gray for secondary elements
textColor = "#333333"  # Dark gray for text
font = "sans serif"
